name: Build and Push to ECR

on:
  workflow_dispatch:
  # push:
  #   branches:
  #     - main  # Change to your deployment branch
permissions:
  id-token: write
jobs:
  build-and-push:
    name: Build & Push Docker Image to ECR
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

     
      - name: configure aws credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          role-to-assume: arn:aws:iam::084828605119:role/github-actions-openid-kish
          role-session-name: githubopenid
          aws-region: eu-north-1

      - name: Log in to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Build Docker image appointment-service
        run: |
          docker build -t hellolambda ./app/hello-world
          docker tag hellolambda:latest 084828605119.dkr.ecr.eu-north-1.amazonaws.com/hellolambda:latest
          
          
      - name: Push Docker image to ECR
        run: |
          docker push 084828605119.dkr.ecr.eu-north-1.amazonaws.com/hellolambda:latest
